GameAdminPanel/Game Admin Panel/Controllers/AnswerController.cs
using System;

using System.Collections.Generic;
//using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Game_Admin_Panel;

namespace Game_Admin_Panel.Controllers
{
    public class AnswerController : Controller
    {
        private Lasta_Entities db = new Lasta_Entities();

        // GET: /Answer/
        public async Task<ActionResult> Index()
        {
            var answers = db.Answers.Include(a => a.ContestDay).Include(a => a.Question).Include(a => a.User);
            return View(await answers.ToListAsync());
        }

        // GET: /Answer/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // GET: /Answer/Create
        public ActionResult Create()
        {
            ViewBag.ContestDayID = new SelectList(db.ContestDays, "ID", "ID");
            ViewBag.QuestionID = new SelectList(db.Questions, "ID", "QuestionContent");
            ViewBag.UserID = new SelectList(db.Users, "ID", "Fullname");
            return View();
        }

        // POST: /Answer/Create
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ContestDayID = new SelectList(db.ContestDays, "ID", "ID", answer.ContestDayID);
            ViewBag.QuestionID = new SelectList(db.Questions, "ID", "QuestionContent", answer.QuestionID);
            ViewBag.UserID = new SelectList(db.Users, "ID", "Fullname", answer.UserID);
            return View(answer);
        }

        // GET: /Answer/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContestDayID = new SelectList(db.ContestDays, "ID", "ID", answer.ContestDayID);
            ViewBag.QuestionID = new SelectList(db.Questions, "ID", "QuestionContent", answer.QuestionID);
            ViewBag.UserID = new SelectList(db.Users, "ID", "Fullname", answer.UserID);
            return View(answer);
        }

        // POST: /Answer/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ContestDayID = new SelectList(db.ContestDays, "ID", "ID", answer.ContestDayID);
            ViewBag.QuestionID = new SelectList(db.Questions, "ID", "QuestionContent", answer.QuestionID);
            ViewBag.UserID = new SelectList(db.Users, "ID", "Fullname", answer.UserID);
            return View(answer);
        }

        // GET: /Answer/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: /Answer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            Answer answer = await db.Answers.FindAsync(id);
            db.Answers.Remove(answer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GameAdminPanel/Game Admin Panel/Views/Answer/Create.cshtml
@model Game_Admin_Panel.Answer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Answer", FormMethod.Post, new { id = "InforAnswer", name = "InforAnswer" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Answer</legend>
        <h2 class="text-title">Vui lòng nhập thông tin đầy đủ của Answer !</h2>
        <div class="registerError">
            @ViewBag.Error
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.QuestionID, "QuestionID", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("QuestionID", String.Empty)
                @Html.ValidationMessageFor(model => model.QuestionID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.UserID, "UserID", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("UserID", String.Empty)
                @Html.ValidationMessageFor(model => model.UserID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.AnswerNumber, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.AnswerNumber)
                @Html.ValidationMessageFor(model => model.AnswerNumber, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ContestDayID, "ContestDayID", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("ContestDayID", String.Empty)
                @Html.ValidationMessageFor(model => model.ContestDayID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Duration, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Duration)
                @Html.ValidationMessageFor(model => model.Duration, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Score, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Score)
                @Html.ValidationMessageFor(model => model.Score, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.IsDeleted, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.IsDeleted)
                @Html.ValidationMessageFor(model => model.IsDeleted, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn" />
        </div>
    </fieldset>
}

@section scripts{

    <script src="~/Scripts/jquery-ui-1.8.24.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#StartTime").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1945:2013"
            });
        });
        $(document).ready(function () {
            $("#CreatedOn").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1945:2013"
            });
        });

        $(function () {
            $('#InforAnswer').validate({
                errorLabelContainer: $("div.registerError"),
                onkeyup: false,
                onfocusout: false,
                invalidHandler: function (form, validator) {
                    $('div.registerError label:not(.error)').remove();
                }
            });

            $('#Fullname').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập họ tên'
                }
            });
            $('#Birthday').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải chọn ngày sinh'
                }
            });
            $('#Address').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập địa chỉ'
                }
            });
            $('#PhoneNumber').rules('add', {
                required: true,
                number: true,
                minlength: 6,
                maxlength: 15,
                messages: {
                    required: 'Bạn phải nhập số điện thoại',
                    number: 'Số điện thoại không hợp lệ',
                    minlength: 'Số điện thoại không hợp lệ',
                    maxlength: 'Số điện thoại không hợp lệ'
                }
            });
            $('#Email').rules('add', {
                required: true,
                Email: true,
                messages: {
                    required: 'Bạn phải nhập địa chỉ Mail',
                    number: 'Địa chỉ Email không hợp lệ'
                }
            });
            $('#Username').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập Username'

                }
            });
            $('#Password').rules('add', {
                required: true,
                minlength: 3,
                maxlength: 15,
                messages: {
                    required: 'Bạn phải nhập Password',
                    minlength: 'Password ít nhất phải 3 - 15 ký tự',
                    maxlength: 'Password không được nhiều hơn 15 ký tự'
                }
            });
            $('#CreatedOn').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải chọn ngày tạo User'
                }
            });


        });

    </script>
}

GameAdminPanel/Game Admin Panel/Views/Answer/Delete.cshtml
@model Game_Admin_Panel.Answer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Answer</legend>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.AnswerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnswerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContestDay.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContestDay.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question.QuestionContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question.QuestionContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Fullname)
        </dd>

    </dl>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

GameAdminPanel/Game Admin Panel/Views/Answer/Details.cshtml
@model Game_Admin_Panel.Answer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Answer</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.AnswerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnswerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContestDay.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContestDay.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question.QuestionContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question.QuestionContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Fullname)
        </dd>

    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GameAdminPanel/Game Admin Panel/Views/Answer/Edit.cshtml
@model Game_Admin_Panel.Answer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Answer</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="control-group">
            @Html.LabelFor(model => model.QuestionID, "QuestionID", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("QuestionID", String.Empty)
                @Html.ValidationMessageFor(model => model.QuestionID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.UserID, "UserID", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("UserID", String.Empty)
                @Html.ValidationMessageFor(model => model.UserID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.AnswerNumber, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.AnswerNumber)
                @Html.ValidationMessageFor(model => model.AnswerNumber, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ContestDayID, "ContestDayID", new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("ContestDayID", String.Empty)
                @Html.ValidationMessageFor(model => model.ContestDayID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Duration, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Duration)
                @Html.ValidationMessageFor(model => model.Duration, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Score, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Score)
                @Html.ValidationMessageFor(model => model.Score, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.IsDeleted, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.IsDeleted)
                @Html.ValidationMessageFor(model => model.IsDeleted, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAdminPanel/Game Admin Panel/Views/Answer/Index.cshtml
@model IEnumerable<Game_Admin_Panel.Answer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AnswerNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContestDay.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Question.QuestionContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Fullname)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AnswerNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContestDay.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Question.QuestionContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Fullname)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>