GameAdminPanel/Game Admin Panel/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Game_Admin_Panel;

namespace Game_Admin_Panel.Controllers
{
    public class TopicController : Controller
    {
        private Lasta_Entities db = new Lasta_Entities();

        // GET: /Topic/
        public async Task<ActionResult> Index()
        {
            return View(await db.Topics.ToListAsync());
        }

        // GET: /Topic/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // GET: /Topic/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Topic/Create
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(topic);
        }

        // GET: /Topic/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: /Topic/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = System.Data.Entity.EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        // GET: /Topic/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = await db.Topics.FindAsync(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: /Topic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Topic topic = await db.Topics.FindAsync(id);
            db.Topics.Remove(topic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GameAdminPanel/Game Admin Panel/Views/Topic/Create.cshtml
@model Game_Admin_Panel.Topic

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Topic", FormMethod.Post, new { id = "InforTopic", name = "InforTopic" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Topic</legend>
        <h2 class="text-title">Vui lòng nhập thông tin đầy đủ Chủ Đề của Câu Hỏi !</h2>
        <div class="registerError">
            @ViewBag.Error
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.TopicContent, "Chủ đề câu hỏi", new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.TopicContent)
                @Html.ValidationMessageFor(model => model.TopicContent, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CreatedOn, "Ngày tạo", new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.IsDeleted, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.IsDeleted)
                @Html.ValidationMessageFor(model => model.IsDeleted, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn" />
        </div>
    </fieldset>
}

@section scripts{

    <script src="~/Scripts/jquery-ui-1.8.24.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#CreatedOn").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1945:2013",
                showOn: 'focus',
                showButtonPanel: true,
                showOtherMonths: true,
                selectOtherMonths: true,

            });
        });

        $(function () {
            $('#InforTopic').validate({
                errorLabelContainer: $("div.registerError"),
                onkeyup: false,
                onfocusout: false,
                invalidHandler: function (form, validator) {
                    $('div.registerError label:not(.error)').remove();
                }
            });

            $('#TopicContent').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập nội dung chủ đề'
                }
            });
            $('#CreatedOn').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải chọn ngày tạo'
                }
            });

        });

    </script>
}

GameAdminPanel/Game Admin Panel/Views/Topic/Delete.cshtml
@model Game_Admin_Panel.Topic

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Topic</legend>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.TopicContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TopicContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

GameAdminPanel/Game Admin Panel/Views/Topic/Details.cshtml
@model Game_Admin_Panel.Topic

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Topic</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.TopicContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TopicContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GameAdminPanel/Game Admin Panel/Views/Topic/Edit.cshtml
@model Game_Admin_Panel.Topic

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>Topic</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="control-group">
            @Html.LabelFor(model => model.TopicContent, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.TopicContent)
                @Html.ValidationMessageFor(model => model.TopicContent, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.IsDeleted, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.IsDeleted)
                @Html.ValidationMessageFor(model => model.IsDeleted, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAdminPanel/Game Admin Panel/Views/Topic/Index.cshtml
@model IEnumerable<Game_Admin_Panel.Topic>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TopicContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TopicContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>