GameAdminPanel/Game Admin Panel/Controllers/ContestDayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Game_Admin_Panel;

namespace Game_Admin_Panel.Controllers
{
    public class ContestDayController : Controller
    {
        private Lasta_Entities db = new Lasta_Entities();

        // GET: /ContestDay/
        public async Task<ActionResult> Index()
        {
            return View(await db.ContestDays.ToListAsync());
        }

        // GET: /ContestDay/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContestDay contestday = await db.ContestDays.FindAsync(id);
            if (contestday == null)
            {
                return HttpNotFound();
            }
            return View(contestday);
        }

        // GET: /ContestDay/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ContestDay/Create
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ContestDay contestday)
        {
            if (ModelState.IsValid)
            {
                db.ContestDays.Add(contestday);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(contestday);
        }

        // GET: /ContestDay/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContestDay contestday = await db.ContestDays.FindAsync(id);
            if (contestday == null)
            {
                return HttpNotFound();
            }
            return View(contestday);
        }

        // POST: /ContestDay/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // 
        // Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ContestDay contestday)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contestday).State = System.Data.Entity.EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contestday);
        }

        // GET: /ContestDay/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContestDay contestday = await db.ContestDays.FindAsync(id);
            if (contestday == null)
            {
                return HttpNotFound();
            }
            return View(contestday);
        }

        // POST: /ContestDay/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ContestDay contestday = await db.ContestDays.FindAsync(id);
            db.ContestDays.Remove(contestday);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GameAdminPanel/Game Admin Panel/Views/ContestDay/Create.cshtml
@model Game_Admin_Panel.ContestDay

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ContestDay", FormMethod.Post, new { id = "InforContestDay", name = "InforContestDay" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>ContestDay</legend>
        <h2 class="text-title">Vui lòng nhập thông tin đầy đủ của ContestDay !</h2>
        <div class="registerError">
            @ViewBag.Error
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.UniqueID, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.UniqueID)
                @Html.ValidationMessageFor(model => model.UniqueID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.NumberOfQuestions, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.NumberOfQuestions)
                @Html.ValidationMessageFor(model => model.NumberOfQuestions, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.IsDeleted, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.IsDeleted)
                @Html.ValidationMessageFor(model => model.IsDeleted, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn" />
        </div>
    </fieldset>
}

@section scripts{

    <script src="~/Scripts/jquery-ui-1.8.24.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#StartTime").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1945:2013"
            });
        });
        $(document).ready(function () {
            $("#CreatedOn").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1945:2013"
            });
        });

        $(function () {
            $('#InforContestDay').validate({
                errorLabelContainer: $("div.registerError"),
                onkeyup: false,
                onfocusout: false,
                invalidHandler: function (form, validator) {
                    $('div.registerError label:not(.error)').remove();
                }
            });

            $('#Fullname').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập họ tên'
                }
            });
            $('#Birthday').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải chọn ngày sinh'
                }
            });
            $('#Address').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập địa chỉ'
                }
            });
            $('#PhoneNumber').rules('add', {
                required: true,
                number: true,
                minlength: 6,
                maxlength: 15,
                messages: {
                    required: 'Bạn phải nhập số điện thoại',
                    number: 'Số điện thoại không hợp lệ',
                    minlength: 'Số điện thoại không hợp lệ',
                    maxlength: 'Số điện thoại không hợp lệ'
                }
            });
            $('#Email').rules('add', {
                required: true,
                Email: true,
                messages: {
                    required: 'Bạn phải nhập địa chỉ Mail',
                    number: 'Địa chỉ Email không hợp lệ'
                }
            });
            $('#Username').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải nhập Username'

                }
            });
            $('#Password').rules('add', {
                required: true,
                minlength: 3,
                maxlength: 15,
                messages: {
                    required: 'Bạn phải nhập Password',
                    minlength: 'Password ít nhất phải 3 - 15 ký tự',
                    maxlength: 'Password không được nhiều hơn 15 ký tự'
                }
            });
            $('#CreatedOn').rules('add', {
                required: true,
                messages: {
                    required: 'Bạn phải chọn ngày tạo User'
                }
            });


        });

    </script>
}

GameAdminPanel/Game Admin Panel/Views/ContestDay/Delete.cshtml
@model Game_Admin_Panel.ContestDay

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ContestDay</legend>

    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.UniqueID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniqueID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfQuestions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfQuestions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}

GameAdminPanel/Game Admin Panel/Views/ContestDay/Details.cshtml
@model Game_Admin_Panel.ContestDay

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ContestDay</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.UniqueID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniqueID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfQuestions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfQuestions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GameAdminPanel/Game Admin Panel/Views/ContestDay/Edit.cshtml
@model Game_Admin_Panel.ContestDay

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="form-horizontal">
        <legend>ContestDay</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="control-group">
            @Html.LabelFor(model => model.UniqueID, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.UniqueID)
                @Html.ValidationMessageFor(model => model.UniqueID, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.NumberOfQuestions, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.NumberOfQuestions)
                @Html.ValidationMessageFor(model => model.NumberOfQuestions, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.CreatedOn, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.CreatedOn)
                @Html.ValidationMessageFor(model => model.CreatedOn, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.IsDeleted, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.IsDeleted)
                @Html.ValidationMessageFor(model => model.IsDeleted, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Save" class="btn" />
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAdminPanel/Game Admin Panel/Views/ContestDay/Index.cshtml
@model IEnumerable<Game_Admin_Panel.ContestDay>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UniqueID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfQuestions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UniqueID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfQuestions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>